config/routes.rb
Rails.application.routes.draw do
  root 'kittens#index'
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, :age, :softness, :cuteness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      flash[:success] = 'New kitten created! Meow!'
      redirect_to @kitten
    else
      flash.now[:error] = 'Double check your form right meow, there might be some missing info!'
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])

    if @kitten.update(kitten_params)
      flash[:success] = 'Kitten update successful! Meow!'
      redirect_to @kitten
    else
      flash.now[:error] = 'Double check your form right meow, there might be some missing info!'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    Kitten.destroy(params[:id])
    flash[:success] = 'Kitten has been released, meow :('
    redirect_to root_path, status: :see_other
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: @kitten do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :age %>
  <%= f.number_field :age %>
  <%= f.label :cuteness %>
  <%= f.number_field :cuteness %>
  <%= f.label :softness %>
  <%= f.number_field :softness %>
  <%= f.submit %>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit the kitten!</h1>

<%= render 'form', kitten: @kitten %>
<%= link_to "Release kitten", @kitten, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>

app/views/kittens/index.html.erb
<h1>Kittens!</h1>

<% @kittens.each do |kitten| %>
  <div>
    <p>Name: <%= kitten.name %></p>
    <p>Age: <%= kitten.age %></p>
    <p>Cuteness: <%= kitten.cuteness %></p>
    <p>Softness: <%= kitten.softness %></p>
    <p><%= link_to "View profile", kitten %></p>
    <p><%= link_to "Release kitten", kitten, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></p>
  </div>
<% end %>

<%= link_to "Create a kitten", new_kitten_path %>

app/views/kittens/new.html.erb
<h1>Create a kitten!</h1>

<%= render 'form', kitten: @kitten %>

app/views/kittens/show.html.erb
<h1>Kitten profile!</h1>

<div>
  <p>Name: <%= @kitten.name %></p>
  <p>Age: <%= @kitten.age %></p>
  <p>Cuteness: <%= @kitten.cuteness %></p>
  <p>Softness: <%= @kitten.softness %></p>
</div>
<%= link_to "Release kitten", @kitten, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
<%= link_to "Edit kitten", edit_kitten_path(@kitten) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <div class="<%= name %>"><%= msg %></div>
    <% end %>
    <%= yield %>
  </body>
</html>